repos:
  - repo: https://github.com/adamchainz/pre-commit-dprint
    rev: "v0.35.3"
    hooks:
      - id: dprint
        pass_filenames: false # https://github.com/adamchainz/pre-commit-dprint/issues/3#issuecomment-1483410008
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.259" # Must match requirements-dev.txt
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.2" # Must match requirements-dev.txt
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0 # Must match .pre-commit-config.yaml
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: "v1.1.300"
    hooks:
      - id: pyright
        args: [--project, Dolphin scripts/pyproject.toml]
ci:
  skip:
    - dprint # https://github.com/adamchainz/pre-commit-dprint/issues/4
    - pyright # https://github.com/RobertCraigie/pyright-python/issues/164
