repos:
  - repo: https://github.com/Avasam/pre-commit-dprint
    rev: "2711573"
    hooks:
      - id: dprint
  # Workaround for https://github.com/adamchainz/pre-commit-dprint/issues/4
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  #   rev: v2.8.0
  #   hooks:
  #     # Moves entire sections, I don't like that >:(
  #     # - id: pretty-format-toml
  #     #   args: [--autofix]
  #     # I don't like it, it really messes up a lot a stuff
  #     # - id: pretty-format-yaml
  #     #   args: [--autofix, --indent, "2", --offset, "0", --preserve-quotes, --line-width, "120"],
  #     - id: pretty-format-ini
  #       args: [--autofix]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.261" # Must match requirements-dev.txt
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.2" # Must match requirements-dev.txt
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0 # Must match .pre-commit-config.yaml
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: "v1.1.302"
    hooks:
      - id: pyright
        args: [--project, Dolphin scripts/pyproject.toml]
ci:
  skip:
    - pyright # https://github.com/RobertCraigie/pyright-python/issues/164
