repos:
  # Workaround for https://github.com/adamchainz/pre-commit-dprint/issues/4
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      # Moves entire sections, I don't like that >:(
      # https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/231
      # - id: pretty-format-toml
      #   args: [--autofix, --trailing-commas, --inline-comment-spaces, "1", --no-sort]
      - id: pretty-format-yaml
        args: [--autofix, --indent, "2", --offset, "2", --preserve-quotes, --line-width, "100"]
      - id: pretty-format-ini
        args: [--autofix]
  - repo: local # https://github.com/dprint/dprint
    hooks:
      - id: dprint
        name: dprint
        entry: dprint fmt
        language: node
        types: [text]
        additional_dependencies: ["dprint@~0.46.0"]
        pass_filenames: false # https://github.com/adamchainz/pre-commit-dprint/issues/3#issuecomment-1483410008
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.10" # Must match requirements-dev.txt
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/hhatto/autopep8
    rev: "v2.3.1" # Must match requirements-dev.txt
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0 # Must match requirements-dev.txt
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: "v1.1.369" # Must match requirements-dev.txt
    hooks:
      - id: pyright

ci:
  autoupdate_schedule: quarterly # Should already be handled by Renovate
  skip:
    - dprint # https://github.com/adamchainz/pre-commit-dprint/issues/4
    - pyright # https://github.com/RobertCraigie/pyright-python/issues/164
