repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
      - id: ruff
  - repo: https://github.com/adamchainz/pre-commit-dprint
    rev: 'v0.35.3'
    hooks:
    -   id: dprint
