name: Verify newsfragments

on:
  workflow_dispatch: #  Allows manual triggers
  push:
    branches:
      - main
    paths:
      - "**/pyproject.toml"
      - "**/newsfragments/**"
      - ".github/workflows/verify_newsfragments.yaml"
      - ".github/verify_newsfragments.py"
  pull_request:
    branches:
      - main
    paths:
      - "**/pyproject.toml"
      - "**/newsfragments/**"
      - ".github/workflows/verify_newsfragments.yaml"
      - ".github/verify_newsfragments.py"

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1

jobs:
  verify_newsfragments:
    name: Verify newsfragments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python .github/verify_newsfragments.py
      - run: python -m pip install towncrier
      # - run: python -m towncrier check
      - run: python -m towncrier build --draft --version check
